### ISSUE TITLE
Database Not Loaded

### ISSUE THREAD

**Issue by RunnerHong** [DanMcInerney/pymetasploit3#62]
when I use `msfrpcd -P msf -S false -p 55552 -U msf`, it raise below error:
```
Traceback (most recent call last):
  File "/home/runner/work/tcr-cmpt-ee/test.py", line 15, in <module>
    workspace = client.db.workspace
  File "/home/runner/work/tcr-cmpt-ee/venv/lib/python3.7/site-packages/pymetasploit3/msfrpc.py", line 1033, in workspace
    return self.rpc.call(MsfRpcMethod.DbCurrentWorkspace)['workspace']
KeyError: 'workspace'

{'error': True, 'error_class': 'Msf::RPC::Exception', 'error_string': 'Msf::RPC::Exception', 'error_backtrace': ["lib/msf/core/rpc/v10/rpc_base.rb:25:in `error'", "lib/msf/core/rpc/v10/rpc_db.rb:97:in `db_check'", "lib/msf/core/rpc/v10/rpc_db.rb:583:in `rpc_current_workspace'", "lib/msf/core/rpc/v10/service.rb:153:in `block in process'", "lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'", "lib/ruby/2.6.0/timeout.rb:33:in `block in catch'", "lib/ruby/2.6.0/timeout.rb:33:in `catch'", "lib/ruby/2.6.0/timeout.rb:33:in `catch'", "lib/ruby/2.6.0/timeout.rb:108:in `timeout'", "lib/msf/core/rpc/v10/service.rb:153:in `process'", "lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:368:in `dispatch_request'", "lib/rex/proto/http/server.rb:302:in `on_client_data'", "lib/rex/proto/http/server.rb:161:in `block in start'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:197:in `each'", "lib/rex/io/stream_server.rb:197:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:106:in `block in spawn'"], 'error_message': 'Database Not Loaded', 'error_code': 500}

```

but when I use `msfconsole -q -x 'load msgrpc Pass=msf'`, it is ok.

please help me solve this problem, thank you.

**Comment by RunnerHong** [comment]
it maybe my local problem
