### ISSUE TITLE
TypeError: 'bool' object is not subscriptable when using "scanner/msmail/onprem_enum"

### ISSUE THREAD

**Issue by mido1677** [DanMcInerney/pymetasploit3#69]
```
>>> auxiliary = client.modules.use('auxiliary', 'scanner/msmail/onprem_enum')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kali/.local/lib/python3.9/site-packages/pymetasploit3/msfrpc.py", line 1669, in use
    return AuxiliaryModule(self.rpc, mname)
  File "/home/kali/.local/lib/python3.9/site-packages/pymetasploit3/msfrpc.py", line 1536, in __init__
    super(AuxiliaryModule, self).__init__(rpc, 'auxiliary', auxiliary)
  File "/home/kali/.local/lib/python3.9/site-packages/pymetasploit3/msfrpc.py", line 1268, in __init__
    if self._moptions[o]['required']:
TypeError: 'bool' object is not subscriptable
```

**Comment by mido1677** [comment]
for this "scanner/msmail/onprem_enum" i installed golang and it's worked!
