### ISSUE TITLE
[ERROR]__init__() got an unexpected keyword argument 'strict_map_key'

### ISSUE THREAD

**Issue by litcu** [DanMcInerney/pymetasploit3#84]
enviroment: Kali Linux, Python 3.9.9
I cannot get my `client` connect to msfrpcd on Kali! I used the commands as follows, which worked well on windows.
```bash
msfrpcd -P QmTp4Atl
python3
>>> from pymetasploit3.msfrpc import MsfRpcClient
>>> client = MsfRpcClient('QmTp4Atl', server="MyIP")
```

When I tried to run `client = MsfRpcClient('QmTp4Atl', server="MyIP")` on Kali, it throw errors like: 
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pymetasploit3/msfrpc.py", line 195, in __init__
    self.login(kwargs.get('username', 'msf'), password)
  File "/usr/local/lib/python3.9/dist-packages/pymetasploit3/msfrpc.py", line 229, in login
    auth = self.call(MsfRpcMethod.AuthLogin, [user, password])
  File "/usr/local/lib/python3.9/dist-packages/pymetasploit3/msfrpc.py", line 222, in call
    return convert(decode(r.content), self.encoding)  # convert all keys/vals to utf8
  File "/usr/local/lib/python3.9/dist-packages/pymetasploit3/utils.py", line 43, in decode
    return msgpack.unpackb(data, strict_map_key=False)
  File "/usr/local/lib/python3.9/dist-packages/msgpack/fallback.py", line 118, in unpackb
    unpacker = Unpacker(None, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict_map_key'
```

I don't know how to solve this problem, could someone help me?

**Comment by DanMcInerney** [comment]
How'd you solve it?

**Comment by conradekisa** [comment]
I danced with this problem as well for abit of time. To the best of my knowledge, there currently isn't a working fix for Python3.9. I had to use [python3.8](https://linuxize.com/post/how-to-install-python-3-8-on-ubuntu-18-04/) and pip3.8(which is installed when you install python3.8). I installed this from source.

With ssl set to True, I was able to get this working.
